---
title: "IA"
author: "Diego Takei"
date: "20 de novembro de 2018"
output: html_document
---

```{r, include=FALSE}
library(tidyverse)
library(caret)
library(ggplot2)
library(dplyr)
library(dataPreparation)
library(tensorflow)
```

```{r}
dadosIniciais <- readr::read_csv(("true_car_listings.csv"),
                           col_types = cols(
                           Year = col_integer(),
                           Price = col_integer(),
                           Mileage = col_integer(),
                           .default = col_character())) %>%
                               mutate(
                               Vin = as.factor(Vin),
                               State = as.factor(State),
                               City = as.factor(City),
                               Make = as.factor(Make),
                               Model = as.factor(Model))
dadosFiltrados <- dadosIniciais %>% sample_n(50000)
dadosTreino <- dadosFiltrados %>% sample_n(40000)
dadosTeste <- dadosFiltrados %>% sample_n(10000)

```

```{r tratamento}
treino <- dadosTreino %>% select(-Vin) %>% mutate_if(is.factor, as.numeric)
teste <- dadosTeste %>% select(-Vin) %>% mutate_if(is.factor, as.numeric)
```

```{r, crossValidation}
ctrl <- trainControl(method = "repeatedcv", 
                     number = 10, 
                     repeats = 10, 
                     verboseIter = FALSE)
cctrl1 <- trainControl(method = "cv", number = 10, returnResamp = "all")
```

```{r KNN}
k <- expand.grid(k = seq(20, 100, length=81))

knnModel <- caret::train(Price ~ Make + Model + State + City + Mileage + Year,
                 data = treino,
                 method = "knn",
                 preProc = c("center", "scale"),
                 trControl = cctrl1,
                 tuneGrid = k)
plot(knnModel)
knnModel
```

```{r MLP with TensorFlow}
mlpModel <- caret::train(Price ~ Make + Model + State + City + Mileage + Year,
                 data = treino,
                 method = "mlpKerasDropout",
                 preProc = c("center", "scale"),
                 trControl = cctrl1,
                 tuneGrid = expand.grid(
                      size = 100, dropout = 0.00, batch_size = 40000, lr = 3, 
                      rho = 0.9, decay = 0, activation = "relu"))
mlpModel
```

```{r MLP without TensorFlow}
mlpModel <- caret::train(Price ~ Make + Model + State + City + Mileage + Year,
                 data = treino,
                 method = "mlp",
                 preProc = c("center", "scale"),
                 trControl = cctrl1,
                 tuneGrid = expand.grid(size = 15))
mlpModel
```

```{r eXtreme Gradient Boosting}
xgModel <- caret::train(Price ~ Make + Model + State + City + Mileage + Year,
                 data = treino,
                 method = "xgbDART",
                 preProc = c("center", "scale"),
                 trControl = cctrl1)
xgModel
plot(xgModel)
```


```{r Random Forest}
forestModel <- caret::train(Price ~ Make + Model + State + City + Mileage + Year,
                 data = treino,
                 method = "cforest",
                 preProc = c("center", "scale"),
                 trControl = cctrl1)
forestModel
```

```{r predict}
knnPredic <- predict(knnModel, teste)
mlpPredic <- predict(mlpModel, teste)

postResample(pred = knnPredic, obs = teste$Price)
postResample(pred = mlpPredic, obs = teste$Price)

```

